### PR TITLE
Fix python-bson -> python-pymongo incompatibility

### PR DESCRIPTION
**Pull request by phansel**
per https://github.com/RobotWebTools/rosbridge_suite/issues/198

per the unresolved https://github.com/ros-noetic-arch/ros-noetic-rosbridge-library/pull/2

### CODE REVIEW

**Comment by phansel** [comment]
also confirmed that this change results in a completed build of the dependent rosbridge_server.

**Comment by phansel** [comment]
@acxz @bionade24 fyi :)

**Comment by phansel** [comment]
@acxz are you still active?

**Comment by phansel** [comment]
orphan request filed at https://aur.archlinux.org/packages/ros-noetic-rosbridge-library :(

**Comment by acxz** [comment]
Sorry @phansel was on vaycay finally back in a bit more capacity now

**Review by acxz — APPROVED** [review]
looks great!

**Comment by acxz** [comment]
thanks so much for your patience!

**Pull request merged**
